controller:
  name: controller
  hostNetwork: false
  daemonset:
    useHostPort: false

  electionID: ingress-controller-leader

  ingressClass: nginx

  kind: DaemonSet

  updateStrategy:
    rollingUpdate:
      maxUnavailable: 10%
    type: RollingUpdate

  livenessProbe:
    failureThreshold: 7
    initialDelaySeconds: 10
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
    port: 10254
  readinessProbe:
    failureThreshold: 7
    initialDelaySeconds: 10
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
    port: 10254

  autoscaling:
    enabled: false

  service:
    enableHttp: true
    enableHttps: true
    targetPorts:
      http: http
      https: https
    type: NodePort
    nodePorts:
      http: 32080
      https: 32443

  config:
    server-tokens: "false"
    use-forwarded-headers: "true"

  stats:
    enabled: false
    service:
      servicePort: 18080
      type: ClusterIP

  metrics:
    enabled: false
    service:
      servicePort: 9913
      type: ClusterIP

revisionHistoryLimit: 10

defaultBackend:
  enabled: true
  name: default-backend
  image:
    repository: k8s.gcr.io/defaultbackend
    tag: "1.3"
    pullPolicy: IfNotPresent

  replicaCount: 1

  minAvailable: 1

  resources: {}

  service:
    servicePort: 80
    type: ClusterIP

rbac:
  create: true

serviceAccount:
  create: true
  name:
